-- Criacao da Tabela Fato com apenas as colunas que são usadas pra esse case.
CREATE TABLE CLIENTS_DEBTS (
	ID_CLIENT NUMERIC(9) NOT NULL,
	CLIENT_NAME VARCHAR (200) NOT NULL,
	CLIENT_EMAIL VARCHAR (200) NOT NULL,
	CLIENT_PHONE_NUMBER VARCHAR (20) NOT NULL,
	ID_DEBIT NUMERIC(9) NOT NULL,
	DEBIT_DESCRIPTION VARCHAR (200) NOT NULL,
	DEBIT_VALUE NUMERIC(11,2) NOT NULL,
	SEND_SMS BIT NOT NULL,
	SEND_EMAIL BIT NOT NULL
);
GO

-- Criacao da XPKCLIENT_DEBITS
ALTER TABLE CLIENTS_DEBTS ADD CONSTRAINT XPKCLIENT_DEBITS PRIMARY KEY NONCLUSTERED (ID_CLIENT, ID_DEBIT);
GO

-- Criacao do index IDXCLIENT_NAME
CREATE INDEX IDXCLIENT_NAME ON CLIENTS_DEBTS (CLIENT_NAME);
GO

-- Criacao da Procedure INSERT_INTO_CLIENTS_DEBITS que ajuda a criacao de registros genéricos na CLIENTS_DEBTS
CREATE PROCEDURE INSERT_INTO_CLIENTS_DEBITS
    @numInserts int
AS
BEGIN
    WHILE @numInserts > 0
    BEGIN
        INSERT INTO CLIENTS_DEBTS SELECT MAX(ID_CLIENT)+1, CONCAT('Cliente', MAX(ID_CLIENT)+1), CONCAT('cliente', MAX(ID_CLIENT)+1, '@gmail.com'), CONCAT('0119979797', MAX(ID_CLIENT)+1), 
MAX(ID_CLIENT)+1, CONCAT('Divida ', MAX(ID_CLIENT)+1), 200000 + MAX(ID_CLIENT)+1, 1,1 FROM CLIENTS_DEBTS;
        set @numInserts = @numInserts - 1
    END
END;

-- Insert inicial na CLIENTS_DEBTS
INSERT INTO CLIENTS_DEBTS VALUES (1, 'Cliente 1', 'cliente1@gmail.com', '011997979701', 1, 'Divida 1', 2000, 0,1);

-- Criacao de 1000 registros na CLIENTS_DEBTS
EXEC INSERT_INTO_CLIENTS_DEBITS 1000;